# Generated by Django 4.0.4 on 2022-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_day_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='image',
            field=models.ImageField(default='Jeti-Oguz-2_2.jpg', null=True, upload_to=''),
        ),
    ]
