# Generated by Django 4.0.4 on 2022-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_day_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='Jeti-Oguz-2_2.jpg', null=True, upload_to='')),
                ('days', models.ManyToManyField(blank=True, related_name='days', to='base.day')),
            ],
        ),
    ]
