# Generated by Django 4.0.4 on 2022-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_day_rooms_tour_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='rooms',
        ),
        migrations.AddField(
            model_name='day',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.room'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(),
        ),
    ]
