# Generated by Django 4.0.4 on 2022-08-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_imagemodel_remove_room_image_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='message',
            field=models.CharField(default='image', max_length=200),
        ),
    ]
