# Generated by Django 4.0.4 on 2022-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_imagemodel_info_imagemodel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='image',
        ),
        migrations.AddField(
            model_name='day',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='base.imagemodel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='photos', to='base.imagemodel'),
        ),
    ]
