# Generated by Django 4.0.4 on 2022-08-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_day_image_day_images_alter_room_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AddField(
            model_name='tour',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='pictures', to='base.imagemodel'),
        ),
    ]
