# Generated by Django 4.0.4 on 2022-08-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_tour_image_tour_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='imgs', to='base.imagemodel')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.location')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='sights',
            field=models.ManyToManyField(blank=True, related_name='sights', to='base.sight'),
        ),
    ]
