# Generated by Django 4.0.4 on 2022-05-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='location',
        ),
    ]
