# Generated by Django 4.0.4 on 2022-05-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_topic_location_rename_topic_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=42.8746, max_digits=100),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=74.5698, max_digits=100),
        ),
    ]
