# Generated by Django 4.0.4 on 2022-07-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
