# Generated by Django 4.0.4 on 2022-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField(blank=True, null=True)),
                ('rooms', models.ManyToManyField(blank=True, related_name='rooms', to='base.room')),
            ],
        ),
    ]
