# Generated by Django 4.0.4 on 2022-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
