# Generated by Django 4.0.4 on 2022-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_tour_rooms_day_rooms_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
